apiVersion: apps/v1
kind: Deployment
metadata:
  name: mayapp
  labels:
    app: myapp
    name: myapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      name: myapp
      labels:
        app: myapp
        release: 1.0
    spec:
      containers:
      - name: myapp
        image: wardviaene/k8s-demo
        ports:
        - containerPort: 3000
